### ISSUE TITLE
5.3 Sprint 1

### ISSUE THREAD

**Issue by SondreH** [vegarr14/404-IS-202#117]
- Hvem gjør hva ? (person abcdef, feks Vegar = A, Erlend = B osvosv, uten å nevne hvem er hvilken bokstav i rapporten (anonymt). Skriv det i gruppechat elns.)
- Hva skal gjøres?
- Ansvars kolonne I sprint backlog
- Ukjent timeestimat. Forklar.
- Skrive om hvorfor ting tok lengre/kortere tid 
 enn planlagt
- Markere om ting er ferdig i backlog?
- Daily scrum: «hvordan fungerer det?

**Comment by vegarr14** [comment]
update:
Daily scrum: «hvordan fungerer det?
og Skrive om hvorfor ting tok lengre/kortere tid
enn planlagt
mangler

**Comment by vegarr14** [comment]
update:
Daily scrum: «hvordan fungerer det? mangler
